version: '3.8'

services:
  laravel_app:
    build:
      context: ./laravel-backend
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./laravel-backend:/var/www
    networks:
      - app-network

  laravel_web:
    image: nginx:alpine
    container_name: laravel_web
    volumes:
      - ./laravel-backend:/var/www
      - ./laravel-backend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - laravel_app
    networks:
      - app-network

  vue_app:
    build:
      context: ./vue3-frontend
      dockerfile: Dockerfile
    container_name: vue_app
    volumes:
      - ./vue3-frontend:/app
    ports:
      - "3000:3000"
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
