version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    ports:
      - "8000:80"
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: laravel_web
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: career_explorer
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
